### ISSUE TITLE
Ajout d'un favoris "indisponible" avec menu ouvert

### ISSUE THREAD

**Issue by alexbonhomme** [Vliller/vliller#44]
Lorsque l'on ajoute un favoris qui est "indisponible" avec le menu favoris ouvert, l'icône est jaune alors qu'elle devrait être grise.

**Comment by manonvbk** [comment]
![22472098_10155679311543898_1752694027_o](https://user-images.githubusercontent.com/22754291/31552488-f46f3bda-b037-11e7-9fec-8b97a2e03a8a.png)

**Comment by alexbonhomme** [comment]
Le bug disparait s'il on ferme et réouvre le menu favoris

**Comment by alexbonhomme** [comment]
Plus d'actualité avec la nouvelle version des favoris qui va arriver
